#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

export DOTFILES="$(dirname $0)"/..
cd $DOTFILES

# Run Homebrew through the Brewfile
if [ "$(uname -s)" == "Darwin" ]
then
  echo "› brew bundle"
  brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
